### ISSUE TITLE
Error in some samples.

### ISSUE THREAD

**Issue by abulenciamiguel** [phac-nml/quasitools#10]
I got this error in some samples.. I'm using version 0.7.0 and the following command:
```
quasitools call ntvar \
sample.bam \
sample.fasta \
-o sample.vcf
```

![image](https://github.com/phac-nml/quasitools/assets/70242638/6aaa6953-bdad-4fab-9581-dce8d4e5012c)

**Comment by yin168** [comment]
Hello,

I got a similar error when running the following command in quasitools 0.7.0. I am wondering whether you resolve this issue and would greatly appreciate it if you could share your solutions.

Thanks a lot!

quasitools call codonvar sample.bam sample.fasta 0 sample.bed

Traceback (most recent call last):
  File "/home/yin168/.conda/envs/cent7/2020.02-py37/quasitools/bin/quasitools", line 10, in <module>
    sys.exit(cli())
  File "/home/yin168/.conda/envs/cent7/2020.02-py37/quasitools/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yin168/.conda/envs/cent7/2020.02-py37/quasitools/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yin168/.conda/envs/cent7/2020.02-py37/quasitools/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yin168/.conda/envs/cent7/2020.02-py37/quasitools/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yin168/.conda/envs/cent7/2020.02-py37/quasitools/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yin168/.conda/envs/cent7/2020.02-py37/quasitools/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yin168/.conda/envs/cent7/2020.02-py37/quasitools/lib/python3.7/site-packages/quasitools/commands/cmd_call.py", line 171, in codonvar
    mapped_read_collection_arr.append(parse_mapped_reads_from_bam(r, bam))
  File "/home/yin168/.conda/envs/cent7/2020.02-py37/quasitools/lib/python3.7/site-packages/quasitools/parsers/mapped_read_parser.py", line 46, in parse_mapped_reads_from_bam
    reference)
  File "/home/yin168/.conda/envs/cent7/2020.02-py37/quasitools/lib/python3.7/site-packages/quasitools/utilities.py", line 28, in sam_alignment_to_padded_alignment
    alignment.reference_end-1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
