### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by jsan4christ** [phac-nml/quasitools#11]
Hi Eric,

Great job here,

Any idea what is causing this error?

Same error on CentOS 7 and Big Sur 11.3.1 M1  chip

quasitools hydra -o results_hydra -cp 30 -rt 2 -md 100 -ma 5 -mf 0.02 fastq/fq_049121_S78_L001_R1_001.fastq.gz fastq/fo_49121_S78_L001_R2_001.fastq.gz
Traceback (most recent call last):
  File "/Users/sanem/miniconda3/envs/sp/bin/quasitools", line 10, in <module>
    sys.exit(cli())
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/quasitools/commands/cmd_hydra.py", line 170, in cli
    patient_analyzer = PatientAnalyzer(id=REFERENCE[REFERENCE.rfind('/')+1:],
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/quasitools/patient_analyzer.py", line 58, in __init__
    self.determine_input_size()
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/quasitools/patient_analyzer.py", line 73, in determine_input_size
    for seq in sequences:
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 72, in __next__
    return next(self.records)
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/Bio/SeqIO/QualityIO.py", line 1123, in iterate
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/site-packages/Bio/SeqIO/QualityIO.py", line 926, in FastqGeneralIterator
    line = next(handle)
  File "/Users/sanem/miniconda3/envs/sp/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by jsan4christ** [comment]
So the solution is shared here;

https://stackoverflow.com/questions/44659851/unicodedecodeerror-utf-8-codec-cant-decode-byte-0x8b-in-position-1-invalid

<img width="747" alt="image" src="https://github.com/phac-nml/quasitools/assets/4986950/8d92a13f-94a3-44c2-b136-ae9093daca4b">

Perhaps updating the codebase to support gzipped files will be helpful as that is the standard for most raw reads.
